services:
  dummy-service:
    build: .
    ports:
      - "5002:80"
    volumes:
      - .:/code
    links:
      - dummy-service-mongodb
  granja_service_events_receiver:
    build: .
    volumes:
      - .:/code
    links:
      - dummy-service-mongodb
    command: python3 app/events.py
  dummy-service-mongodb:
    image: mongo:5.0
    volumes:
      - dummy-service-mongodb-container:/data/db
    logging:
        driver: none

volumes:
  dummy-service-mongodb-container:

networks:
  default:
    name: microsvcs
    external: true