services:
  granja-service:
    build: .
    ports:
      - "5001:80"
    volumes:
      - .:/code
    links:
      - granja-service-mongodb
  granja-service-events-receiver:
    build: .
    volumes:
      - .:/code
    links:
      - granja-service-mongodb
    command: python3 app/events.py
  granja-service-mongodb:
    image: mongo:5.0
    volumes:
      - granja-service-mongodb-container:/data/db
    logging:
        driver: none

volumes:
  granja-service-mongodb-container:

networks:
  default:
    name: microsvcs
    external: true